[package]
name = "unet"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
colored = "2.1.0"
console = "0.15.8"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros", "time"]}
futures = "0.3.30"